import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Footer from "../components/footer";
import Navbar from "@/components/Navbar";
import MainPage from "@/components/MainPage";
import SideBar from "@/components/SideBar";
import { SetStateAction, useState } from "react";
import Searchbar from "@/components/searchbar";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false"
  );
  const crypto = await res.json();
  return {
    props: {
      crypto,
    },
  };
};
export default function Home({ crypto }: any) {
  const [search, setSearch] = useState("");
  const handleChange = (e: any) => {
    e.preventDefault();
    setSearch(e.target.value.toLowerCase());
    console.log(search);
  };
  const allCoins = crypto.filter((coin: any) =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-hidden">
        <Navbar />
        <Searchbar onChange={handleChange} />
        <div className="flex">
          <div className="md:w-1/5 w-0">
            <SideBar />
          </div>
          <div className="md:w-4/5 h-2/6 w-full overflow-y-hidden">
            <MainPage crypto={allCoins} onChange={handleChange} />
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
